import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import StoreProvider from "../store/storeProvider";
import Header from "../components/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider attribute="class" defaultTheme="light">
          <StoreProvider>
            <div className="relative min-h-screen">
              <Header />
              <main className="pt-16">{children}</main>
            </div>
        {/* <ToastContainer
            position="top-center"
            autoClose={1000}
            hideProgressBar={false}
            newestOnTop={false}
            closeOnClick
            rtl={false}
            pauseOnFocusLoss
            draggable
            pauseOnHover
            /> */}
          </StoreProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
